DATASET:
  root_dataset: "//philly/rr1/public/v-miyin/data/cityscapes/"
  list_train: "./data/cityscapes_train.odgt"
  list_val: "./data/cityscapes_val.odgt"
  num_class: 19
  imgSizes: (600,)
  imgMaxSize: 1280
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet101dilated"
  arch_decoder: "nonlocal_deepsup"
  fc_dim: 2048
  downsample: False
  whiten_type: []
  temp: 1.0
  with_gc: False
  use_out: True
  out_bn: True

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 12
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_12.pth"

TEST:
  checkpoint: "epoch_12.pth"
  result: "./"

DIR: "ckpt/cityscapes-resnet101dilated-nonlocal"
